--- # Master Playbook for Web Servers
- hosts: apacheserver
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: when did the ROLE start
    raw: date > /home/ansible/startofrole.log
  roles:
    - webservers
  post_tasks:
  - name: When did the ROLE end
    raw: date > /home/ansible/endofrole.log
